---
title: "Untitled"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
packages = c('ggstatsplot', 'ggside', 
             'tidyverse', 'ggdist', 'PMCMRplus')

for(p in packages){library
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

```{r}
exam <- read_csv("data/Exam_data.csv")
```

```{r}
set.seed(1234)

gghistostats(
  data = exam,
  x = ENGLISH,
  test.value = 60,
  xlab = "English scores"
)
```

```{r}

gghistostats(
  data = exam,
  x = ENGLISH,
  type = 'np',
  test.value = 60,
  xlab = "English scores"
)
```

```{r}
set.seed(1234)

gghistostats(
  data = exam,
  x = ENGLISH,
  type = 'bayes',
  test.value = 60,
  xlab = "English scores"
)
```


```{r}
ggbetweenstats(
  data = exam,
  x = GENDER, 
  y = MATHS,
  type = 'np',
  messages = FALSE
)
```

```{r}
ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "p",
  mean.ci = TRUE, 
  pairwise.comparisons = TRUE, 
  pairwise.display = "s",
  p.adjust.method = "fdr",
  messages = FALSE
)
```

```{r}
packages = c('readxl', 'report', 'performance', 
             'parameters', 'see')
for(p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

