---
title: "Parallel Coordinates"
description: |
  A new article created using the Distill format.
author:
  - name: Nora Jones 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
packages = c('GGally', 'parcoords', 'parallelPlot', 'tidyverse')

for(p in packages){library
  if(!require(p, character.only = T)){
    install.packages(p)
  }
  library(p, character.only = T)
}
```

```{r}
wh <- read_csv("data/WHData-2018.csv")
```

```{r, fig.height=12, fig.width=12}
ggparcoord(data = wh, 
           columns = c(7:12))
```

```{r, fig.height=12, fig.width=12}
ggparcoord(data = wh, 
           columns = c(7:12))
```

```{r, fig.height=12, fig.width=12}
ggparcoord(data = wh, 
           columns = c(7:12), 
           groupColumn = 2,
           scale = "uniminmax",
           alphaLines = 0.2,
           boxplot = TRUE, 
           title = "Parallel Coord. Plot of World Happines Attributes")
```







